### ISSUE TITLE
Complete tasks from Maicol's workshop

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/shared-housing#200]
### Overview
Maicol's workshop outlined several big tasks our team needs to complete, and put them all on post its assigned to different team members. This epic is to keep track of all the tasks and what state they're in.

### Action Items

- [ ] Gather questions from Shared Housing team members and get answers from LAFH #189  

- [ ] Review business process map #188 

- [ ] Create reports of key findings for client and Shared Housing teams #190 and #191 

- [ ] Create lists of knowns and unknowns for each team to populate and update #192 

- [ ] Identify what data the client has available to them #193 

- [ ] Create a well-defined list of features for an MVP #194 

### Resources/Instructions
@c-fuchs add pictures of board here
