### ISSUE TITLE
Define Discovery milestones and Artifacts

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#43]
### Overview
We've begun discussing what the first milestone for this project might look like, including tasks and artifacts. Let's memorialize them here, then implement them on the project board.

### Action Items
- [x] codify suggested milestone items
- [x] create milestone on project board
- [x] include existing cards relating to milestone
- [x] create issues / cards for any missing milestones

### Resources
Suggested Milestones / Artifacts (from 7/09 meeting):
- Must haves
  - Absolutely need to finish “expert interviews”
  - ID Problems we want to solve for
  - LAfH service map (current)
    - detail pain points
- Nice to haves
  - “persona” interviews
  - Mental model diagram
  - Empathy maps

### Questions
What artifacts do we want to have produced as a result of this process?

**Comment by owenjoseph** [comment]
@awadethomas took the exercise we ran last week and organized everything into several milestones, including potential deliverables:

https://docs.google.com/document/d/1DXAbC4vxSYboqxn_d0RFRTP3LCW4HM1Z35G1xFxw01k/edit?usp=sharing

Next steps would be to present this to the group for feedback at hacknight.

**Comment by awadethomas** [comment]
@abregorivas wanted to connect you to this item, as it is where we'll continually groom our milestones

**Comment by awadethomas** [comment]
Next potential steps here are to add when we will need members of the LA Family Housing team on site to point out to Kris and Dan as we continue our conversations with them. We need to set the expectation.

**Comment by awadethomas** [comment]
@owenjoseph looking more at the doc, it already calls out when we will need client involvement. what did we mention we might want to include?

**Comment by owenjoseph** [comment]
In the interest of cleaning up this board, I'm going to close this, as I think we've got a good system for tracking milestone progress in place now, and the grooming will be part of an ongoing effort.
