### ISSUE TITLE
Informational Interviews

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#93]
### Overview
The goal of the Informational Interviews is to help us understand the LAFH shared housing process as it currently exists. In order to achieve that goal, we want to conduct 1-hour, in-person interviews with at least one representative from each team involved in the Shared Housing Process:

- Location
- Navigation
- Stabilization
- Outreach

The output of each of these interviews should be:
- audio of interview
- transcript of interview
- high-level insights (incl. key takeaways)

### Sub-tasks
- [x] Locations Interview
  - [x] Archive Interview Artifacts
  - [x] High-Level Insights document
- [x] Navigator Interview
  - [x] Archive Interview Artifacts
  - [x] High-Level Insights document
- [x] Stabilization Interview
  - [x] Archive Interview Artifacts
  - [x] High-Level Insights document
- [x] Outreach Interview
  - [x] Archive Interview Artifacts
  - [x] High-Level Insights document

**Comment by owenjoseph** [comment]
Hey we closed out our first Epic!

🎉 🎉 🎉

**Comment by owenjoseph** [comment]
Find all interview artifacts and insight documents here: https://drive.google.com/open?id=1vqR5xfPRvVpvk-fzNzGrjvKRwuR6BNOP
